export const trendingNew = [
  {
    title: "Kanimaa",
    artist: "Santhosh Narayanan & The Indian Choral Ensemble",
    genre: "Film soundtrack / Dance-pop",
    release_date: "2025-03-21",
    type: "jpg",
    album: "Retro",
  },
  {
    title: "Kannadi Poove",
    artist: "Santhosh Narayanan",
    genre: "Film soundtrack / Romantic",
    release_date: "2025-02-13",
    type: "jpg",
    album: "Retro",
  },
  {
    title: "The One",
    artist: "Santhosh Narayanan",
    genre: "Film soundtrack / Energetic",
    release_date: "2025-04-12",
    type: "webp",
    album: "Retro",
  },
  {
    title: "Muththa Mazhai",
    artist: "Dhee (original), Chinmayi Sripada (reprise)",
    genre: "Melodic / Classical-inspired",
    release_date: "2025-05-24",
    type: "jpg",
    album: "Thug Life",
  },
  {
    title: "Jinguchaa",
    artist: "A. R. Rahman",
    genre: "Upbeat / Film soundtrack",
    type: "webp",
    release_date: "2025 (album release May 24)",
    album: "Thug Life",
  },
  {
    title: "Vinveli Nayaga",
    artist: "Shruti Haasan",
    genre: "Emotional ballad / Tribute",
    type: "jpg",
    release_date: "2025 (Thug Life soundtrack)",
    album: "Thug Life",
  },
  {
    title: "Pathikichu",
    artist: "Anirudh Ravichander",
    genre: "Dance-floor / Energetic",
    type: "jpg",
    release_date: "2025-01-19",
    album: "Vidaamuyarchi",
  },
  {
    title: "Sawadeeka",
    artist: "Anthony Daasan & Anirudh Ravichander",
    genre: "Dance-pop / Celebration",
    type: "jpg",
    release_date: "2024-12-27",
    album: "Vidaamuyarchi",
  },
  {
    title: "Monica",
    artist: "Anirudh Ravichander, Sublahshini, Asal Kolaar",
    genre: "Hip-Hop / Party Anthem",
    release_date: "2025-06-10",
    type: "jpg",
    album: "Coolie",
  },
  {
    title: "Powerhouse",
    artist: "Anirudh Ravichander, Arivu",
    genre: "Electro Fusion / Political Rap",
    release_date: "2025-07-01",
    type: "jpg",
    album: "Coolie",
  },
];

export const madeForYou = [
  {
    title: "Achacho",
    artist: "Hiphop Tamizha",
    genre: "Hiphop / Film fun",
    type: "jpg",
    release_date: "2025",
    album: "Aranmanai 4",
  },
  {
    title: "Sugar Baby",
    artist: "A. R. Rahman / Thug Life",
    genre: "Film soundtrack / Upbeat",
    type: "webp",
    release_date: "2025",
    album: "Thug Life",
  },
  {
    title: "Golden Sparrow",
    artist: "GV Prakash Kumar",
    genre: "Pop / Film music",
    type: "jpg",
    release_date: "2025",
    album: "NEEK",
  },
  {
    title: "OG Sambavam",
    artist: "GV Prakash Kumar",
    genre: "Energetic / Film soundtrack",
    type: "jpg",
    release_date: "2025",
    album: "Good Bad Ugly",
  },
  {
    title: "Manasilaayo",
    artist: "Anirudh Ravichander",
    genre: "Energetic / Film soundtrack",
    type: "jpg",
    release_date: "2025",
    album: "Vettaiyan",
  },
  {
    title: "Vazhithunaiye",
    artist: "Leon James",
    genre: "Contemporary / Film soundtrack",
    type: "jpg",
    release_date: "2025",
    album: "Dragon",
  },
  {
    title: "Hey Minnale",
    artist: "GV Prakash Kumar",
    genre: "Film duet / Melodic",
    type: "jpg",
    release_date: "2025",
    album: "Amaran",
  },
  {
    title: "Maatikkinaaru Orutharu",
    artist: "Leon James",
    genre: "Film fun / Upbeat",
    type: "jpg",
    release_date: "2025",
    album: "Dragon",
  },
  {
    title: "Kallaliye Kallaliye",
    artist: "Hesham Abdul Wahab",
    genre: "Romantic / Film soundtrack",
    type: "jpg",
    release_date: "2025",
    album: "Maaman",
  },
  {
    title: "Minikki Minikki",
    artist: "GV Prakash Kumar",
    genre: "Energetic / Film",
    type: "jpg",
    release_date: "2025",
    album: "Thangalaan",
  },
];

export const englishSongs = [
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop / Dancehall",
    release_date: "2017-01-06",
    type: "png",
    album: "÷ (Divide)",
  },
  {
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Synthwave / Pop",
    release_date: "2019-11-29",
    type: "png",
    album: "After Hours",
  },
  {
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "Disco / Pop",
    release_date: "2020-10-01",
    type: "jpg",
    album: "Future Nostalgia",
  },
  {
    title: "Blue",
    artist: "Yung Kai",
    genre: "Alternative / Pop",
    release_date: "2024",
    type: "png",
    album: "Blue",
  },
  {
    title: "The Hanging Tree",
    artist: "Jennifer Lawrence",
    genre: "Soundtrack / Folk",
    release_date: "2014-11-21",
    type: "jpg",
    album: "The Hunger Games: Mockingjay – Part 1",
  },
  {
    title: "APT",
    artist: "Rosé, Bruno Mars",
    genre: "Electronic / Dance",
    release_date: "2021-05-21",
    type: "png",
    album: "Memories... Do Not Open",
  },
  {
    title: "I Wanna Be Yours",
    artist: "Arctic Monkeys",
    genre: "Indie Rock / Alternative",
    release_date: "2014-09-29",
    type: "jpg",
    album: "AM",
  },
  {
    title: "Night Changes",
    artist: "One Direction",
    genre: "Pop / Ballad",
    release_date: "2014-11-14",
    type: "png",
    album: "Four",
  },
  {
    title: "Summertime Sadness",
    artist: "Lana Del Rey",
    genre: "Indie Pop / Dream Pop",
    release_date: "2012-06-22",
    type: "jpg",
    album: "Born to Die",
  },
  {
    title: "Rolling in the Deep",
    artist: "Adele",
    genre: "Soul / Pop",
    release_date: "2010-11-29",
    type: "png",
    album: "21",
  },
];
